---
hostname: vMX-1
fxp0_address: 192.168.1.201

role: pe
asn: '7990'
vendor: juniper
model: mx

snmp_desc: 'My vMX-1'
snmp_location: 'Foghorn Chicken Shed'
snmp_contact: 'Rooster'

ports:
  - port: lo0
    desc: 'vMX-1 Loopback'
    unit: 
      - number: 0
        ipv4_address: 1.1.1.1/32
        ospf: 1
        area: 0.0.0.0
        passive: 1

  - port: ge-0/0/0
    desc: 'To vMX-2'
    unit: 
      - number: 0
        ipv4_address: 185.80.1.1/30
        ospf: 1
        area: 0.0.0.0

  - port: ge-0/0/1
    desc: 'To vMX-3'
    unit:
      - number: 0
        ipv4_address: 185.80.1.5/30i
  
  - port: irb
    unit: 
      - number: 10
        desc: 'To servers'
        ipv4_address: 9.9.9.1/24

vlans:
  - vlan: 10
    name: 'TO-SERVERS'
    desc: 'Server VLAN'
    l3interface: yes
        

bgp:
  - peer: 1.1.1.2
    group: IBGP
    peeras: 7990
    desc: 'IBGP to vMX-2'

